version: "3"
services:
  cms_app:
    build: ./app
    container_name: cms_app
    volumes:
      - ./app:/app
      - ../../libs:/libs
    environment:
      - DB_HOST=cms_db
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - FLASK_ENV=${FLASK_ENV}
      - LC_ALL=${LANG}
      - LANG=${LANG}
      - VIRTUAL_PORT=${SERVICE_PORT}
    ports:
      - "127.0.0.1:${SERVICE_PORT}:${SERVICE_PORT}"
    links:
      - cms_db
  cms_db:
    build: ./db
    container_name: cms_db
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/backup:/backup
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_DBNAME=${DB_NAME}
      - POSTGRES_PASS=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - VIRTUAL_PORT=${DB_PORT}
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
